import type { StoredConcept } from './conceptStorage';

function getGradeLetter(score: number): string {
  if (score >= 90) return 'A+';
  if (score >= 85) return 'A';
  if (score >= 80) return 'A-';
  if (score >= 75) return 'B+';
  if (score >= 70) return 'B';
  if (score >= 60) return 'C+';
  if (score >= 50) return 'C';
  return 'D';
}

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return '█'.repeat(filled) + '░'.repeat(10 - filled);
}

export function exportConceptsAsPDF(concepts: StoredConcept[]): void {
  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Concept Forge Export</title>
<style>
  @page { margin: 40px 50px; }
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px 20px; }
  .cover { text-align: center; padding: 60px 0 40px; border-bottom: 3px solid #000; margin-bottom: 40px; }
  .cover h1 { font-size: 32px; font-weight: 900; letter-spacing: 2px; margin: 0; }
  .cover .subtitle { font-size: 14px; color: #666; margin-top: 8px; }
  .concept { page-break-inside: avoid; margin-bottom: 50px; padding-bottom: 30px; border-bottom: 1px solid #e0e0e0; }
  .concept-num { font-size: 11px; font-weight: 700; letter-spacing: 3px; color: #999; text-transform: uppercase; margin-bottom: 8px; }
  .headline { font-size: 24px; font-weight: 800; line-height: 1.2; margin: 0 0 6px; }
  .tagline { font-size: 16px; font-style: italic; color: #555; margin: 0 0 16px; }
  .device { display: inline-block; background: #f0f0f0; padding: 3px 10px; font-size: 11px; font-weight: 600; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 16px; }
  .section-label { font-size: 10px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #888; margin: 16px 0 4px; }
  .body-copy { font-size: 14px; line-height: 1.7; color: #333; }
  .visual { font-size: 13px; color: #555; font-style: italic; background: #fafafa; padding: 12px; border-left: 3px solid #ddd; }
  .scores { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 16px; }
  .score-card { text-align: center; padding: 8px 14px; background: #f8f8f8; border-radius: 6px; min-width: 80px; }
  .score-grade { font-size: 20px; font-weight: 900; }
  .score-label { font-size: 9px; letter-spacing: 1px; text-transform: uppercase; color: #888; }
  .score-pct { font-size: 11px; color: #aaa; font-family: monospace; }
  .prompt { font-size: 12px; color: #888; font-style: italic; margin-top: 12px; }
  .footer { text-align: center; font-size: 11px; color: #aaa; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; }
  .grade-a { color: #059669; } .grade-b { color: #2563EB; } .grade-c { color: #D97706; } .grade-d { color: #DC2626; }
</style></head><body>
<div class="cover">
  <h1>CONCEPT FORGE</h1>
  <div class="subtitle">${concepts.length} Concept${concepts.length !== 1 ? 's' : ''} • Exported ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</div>
</div>
${concepts.map((c, i) => {
  const scores = [
    { label: 'Originality', value: c.originalityScore },
    { label: 'Professional', value: c.professionalismScore },
    { label: 'Clarity', value: c.clarityScore },
    { label: 'Freshness', value: c.freshnessScore },
    { label: 'Resonance', value: c.resonanceScore },
    { label: 'Awards', value: c.awardsScore },
  ].filter(s => s.value && s.value > 0);

  return `<div class="concept">
  <div class="concept-num">Concept ${i + 1}</div>
  <div class="headline">${esc(c.headlines[0] || 'Untitled')}</div>
  ${c.tagline ? `<div class="tagline">${esc(c.tagline)}</div>` : ''}
  <div class="device">${esc(c.rhetoricalDevice)}</div>
  ${c.bodyCopy ? `<div class="section-label">Body Copy</div><div class="body-copy">${esc(c.bodyCopy)}</div>` : ''}
  ${c.visualDescription ? `<div class="section-label">Visual Concept</div><div class="visual">${esc(c.visualDescription)}</div>` : ''}
  ${scores.length > 0 ? `<div class="section-label">Quality Scores</div><div class="scores">${scores.map(s => {
    const grade = getGradeLetter(s.value!);
    const cls = grade.startsWith('A') ? 'grade-a' : grade.startsWith('B') ? 'grade-b' : grade.startsWith('C') ? 'grade-c' : 'grade-d';
    return `<div class="score-card"><div class="score-grade ${cls}">${grade}</div><div class="score-label">${s.label}</div><div class="score-pct">${s.value}%</div></div>`;
  }).join('')}</div>` : ''}
  <div class="prompt">Brief: "${esc(c.prompt)}"</div>
</div>`;
}).join('\n')}
<div class="footer">Generated by Concept Forge • thecforge.com</div>
</body></html>`;

  downloadBlob(html, 'text/html', `concept-forge-export-${Date.now()}.html`);
}

export function exportConceptsAsPresentation(concepts: StoredConcept[]): void {
  const slides = concepts.map((c, i) => {
    const scores = [
      { label: 'ORI', value: c.originalityScore },
      { label: 'PRO', value: c.professionalismScore },
      { label: 'CLR', value: c.clarityScore },
      { label: 'FRS', value: c.freshnessScore },
      { label: 'RES', value: c.resonanceScore },
      { label: 'AWD', value: c.awardsScore },
    ].filter(s => s.value && s.value > 0);

    return `<div class="slide">
  <div class="slide-num">${String(i + 1).padStart(2, '0')}</div>
  <h1>${esc(c.headlines[0] || 'Untitled')}</h1>
  ${c.tagline ? `<h2>${esc(c.tagline)}</h2>` : ''}
  <div class="device-tag">${esc(c.rhetoricalDevice)}</div>
  ${c.bodyCopy ? `<p class="body">${esc(c.bodyCopy)}</p>` : ''}
  ${c.visualDescription ? `<div class="visual-block"><span class="vl">VISUAL DIRECTION</span><p>${esc(c.visualDescription)}</p></div>` : ''}
  ${scores.length > 0 ? `<div class="score-row">${scores.map(s => 
    `<div class="score-pill"><span class="sp-val">${s.value}</span><span class="sp-lbl">${s.label}</span></div>`
  ).join('')}</div>` : ''}
</div>`;
  });

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Concept Forge Presentation</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; background: #0a0a0a; color: #fff; }
  .slide { min-height: 100vh; display: flex; flex-direction: column; justify-content: center; padding: 60px 80px; page-break-after: always; position: relative; }
  .slide-num { position: absolute; top: 40px; right: 60px; font-size: 48px; font-weight: 900; color: rgba(255,255,255,0.06); }
  .slide h1 { font-size: 48px; font-weight: 900; line-height: 1.1; max-width: 80%; margin-bottom: 12px; }
  .slide h2 { font-size: 22px; font-weight: 400; color: #67e8f9; font-style: italic; margin-bottom: 24px; }
  .device-tag { display: inline-block; border: 1px solid rgba(255,255,255,0.2); padding: 4px 14px; font-size: 11px; letter-spacing: 2px; text-transform: uppercase; color: rgba(255,255,255,0.5); margin-bottom: 30px; }
  .body { font-size: 18px; line-height: 1.7; color: rgba(255,255,255,0.8); max-width: 700px; margin-bottom: 24px; }
  .visual-block { background: rgba(255,255,255,0.05); border-left: 3px solid rgba(255,255,255,0.15); padding: 16px 20px; margin-bottom: 24px; max-width: 700px; }
  .vl { font-size: 9px; letter-spacing: 2px; color: rgba(255,255,255,0.35); display: block; margin-bottom: 6px; }
  .visual-block p { font-size: 14px; color: rgba(255,255,255,0.6); font-style: italic; }
  .score-row { display: flex; gap: 12px; margin-top: 20px; }
  .score-pill { background: rgba(255,255,255,0.08); border-radius: 8px; padding: 10px 16px; text-align: center; min-width: 60px; }
  .sp-val { display: block; font-size: 22px; font-weight: 800; color: #60A5FA; }
  .sp-lbl { display: block; font-size: 9px; letter-spacing: 1px; color: rgba(255,255,255,0.4); margin-top: 2px; }
  @media print { .slide { height: 100vh; } }
</style></head><body>
<div class="slide" style="justify-content: center; align-items: center; text-align: center;">
  <h1 style="font-size: 56px; max-width: 100%;">CONCEPT FORGE</h1>
  <p style="font-size: 16px; color: rgba(255,255,255,0.4); margin-top: 16px;">${concepts.length} Creative Concepts</p>
  <p style="font-size: 12px; color: rgba(255,255,255,0.25); margin-top: 8px;">${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
</div>
${slides.join('\n')}
<div class="slide" style="justify-content: center; align-items: center; text-align: center;">
  <p style="font-size: 14px; color: rgba(255,255,255,0.3);">Generated by Concept Forge • thecforge.com</p>
</div>
</body></html>`;

  downloadBlob(html, 'text/html', `concept-forge-deck-${Date.now()}.html`);
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function downloadBlob(content: string, type: string, filename: string): void {
  const blob = new Blob([content], { type: `${type};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
